app/django/app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.utils.text import format_lazy
from django.utils.translation import ugettext_lazy as _, pgettext_lazy

import web.views as views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rosetta/', include('rosetta.urls'))
]

urlpatterns += i18n_patterns(
    url(
        format_lazy(r'^{0}$', pgettext_lazy('Dio URL-a', 'login')),
        views.LoginView.as_view(),
        name='login'
    ),
    url(
        format_lazy(r'^{0}$', pgettext_lazy('Dio URL-a', 'logout')),
        views.LogoutView.as_view(),
        name='logout'
    ),
    url(
        format_lazy(r'^{0}$', pgettext_lazy('Dio URL-a', 'registracija')),
        views.RegisterView.as_view(),
        name='register'
    ),
    url(
        # doubles braces to avoid clash between regex syntax and python formatting
        format_lazy(
            r'^{0}/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{{1,13}}-[0-9A-Za-z]{{1,20}})$',
            pgettext_lazy('Dio URL-a', 'registracija')
        ),
        views.RegisterConfirmView.as_view(),
        name='register_confirm'
    ),
    url(
        format_lazy(r'^{0}$', pgettext_lazy('Dio URL-a', 'lozinka')),
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    url(
        format_lazy(
            r'^{0}/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{{1,13}}-[0-9A-Za-z]{{1,20}})$',
            pgettext_lazy('Dio URL-a', 'lozinka')
        ),
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    url(
        format_lazy(r'^{0}$', pgettext_lazy('Dio URL-a', 'algoritmi')),
        views.AlgorithmList.as_view(),
        name='algorithm_list'
    ),
    url(
        format_lazy(
            r'^{0}/(?P<pk>[0-9a-f]{{8}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{12}})$',
            pgettext_lazy('Dio URL-a', 'algoritmi')
        ),
        views.AlgorithmDetail.as_view(),
        name='algorithm'
    ),
    url(
        format_lazy(r'^{0}$', pgettext_lazy('Dio URL-a', 'nova-obrada')),
        views.IterationCreateView.as_view(),
        name='iteration_create'
    ),
    url(
        r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$',
        views.IterationView.as_view(),
        name='iteration'
    ),
    url(r'^$', views.HomeView.as_view(), name='home'),
)

if settings.DEBUG:

    #from debug_toolbar import urls

    # urlpatterns.append(url(r'^__debug__/', include(urls)))
    urlpatterns.extend(staticfiles_urlpatterns())
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/django/web/models.py
import os
import uuid

from django.conf import settings
from django.urls import reverse
from django.utils.functional import cached_property
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from django_utils.abstract import TimestampModel

from web.service import upload_path_exe, upload_path_input_data


class Algorithm(TimestampModel):
    """
    Information and binaries connected to an algorithm/application for remote execution.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(verbose_name='naziv', max_length=255, unique=True)
    file = models.CharField(
        verbose_name='Full path applikacije s imenom', max_length=4096,
        blank=True, help_text="npr. /home/igork/rExe/run_rExeApp.sh"
    )
    matlab_runtime_path = models.CharField(
        verbose_name="Matlab Runtime Direktorij", max_length=4096, blank=True,
        help_text="npr. /usr/local/MATLAB/MATLAB_Runtime/v85/"
    )
    description = models.TextField(verbose_name='opis', blank=True)
    document = models.FileField(verbose_name='datoteka dokumentacije', blank=True, upload_to=upload_path_exe)
    source = models.FileField(verbose_name='datoteka source kȏda', blank=True, upload_to=upload_path_exe)
    is_active = models.BooleanField(
        verbose_name='aktivno',
        default=True,
        help_text='Neaktivan algoritam se neće prikazivati kao opcija korisnicima.'
    )
    auto_add = models.BooleanField(
        verbose_name='automatski pristup korisnicima',
        default=True,
        help_text='Omogućiti kako bi se novi registrirani korisnici automatski dodali u listu korisnika s pristupom.'
    )
    users = models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='korisnici s pristupom', blank=True)

    class Meta:
        verbose_name = 'algoritam'
        verbose_name_plural = 'algoritmi'
        db_table = 'algorithm'
        ordering = ('-created',)

    def __str__(self):
        return self.name


class Iteration(TimestampModel):
    """
    A single iteration of algorith execution and all connected input/output data.
    """
    START = 1
    FAILURE = -1
    SUCCESS = 0
    STATUS_CHOICES = (
        (START, _('izvršavanje u tijeku')),
        (FAILURE, _('neuspješno završeno')),
        (SUCCESS, _('uspješno završeno')),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    input_data = models.FileField(verbose_name='ulazni podaci', upload_to=upload_path_input_data, max_length=511)
    output_data = models.FileField(verbose_name='izlazni podaci', blank=True, max_length=511)
    status_code = models.SmallIntegerField(
        verbose_name='statusni kod',
        choices=STATUS_CHOICES,
        null=True,
        blank=True,
        default=START
    )
    status_message = models.TextField(verbose_name='statusna poruka', blank=True)
    mail_on_completion = models.BooleanField(verbose_name='pošalji rezultate na mail', default=False)
    mailed = models.DateTimeField(verbose_name='poslano', null=True)
    finished = models.DateTimeField(verbose_name='završetak', null=True)

    algorithm = models.ForeignKey(to='web.Algorithm', verbose_name='algoritam', on_delete=models.PROTECT)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, verbose_name='korisnik', on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'iteracija algoritma'
        verbose_name_plural = 'iteracije algoritma'
        db_table = 'algorithm_iteration'
        ordering = ('-created', 'algorithm')

    def __str__(self):
        return str(self.id)

    def _is_image(self, file_data):
        from PIL import Image

        try:
            image = Image.open(str(self.input_data))

        except (OSError, ValueError) as exc:
            # not an image
            return False

        else:
            image.verify()
            return True

    @property
    def input_is_image(self):
        return  self._is_image(file_data=self.input_data)

    @property
    def output_is_image(self):
        return self._is_image(file_data=self.output_data)

    @property
    def started(self):
        return self.status_code == self.START

    @property
    def failed(self):
        return self.status_code == self.FAILURE

    @property
    def successful(self):
        return self.status_code == self.SUCCESS

    @cached_property
    def iteration_number(self):
        manager = self.__class__.objects

        if self.created is None:
            number = manager.filter(algorithm=self.algorithm, user=self.user, created__lte=now()).count() + 1
        else:
            number = manager.filter(algorithm=self.algorithm, user=self.user, created__lte=self.created).count()

        return number

    @property
    def input_directory(self):
        return self._data_directory('in')

    @property
    def output_directory(self):
        return self._data_directory('out')

    def _data_directory(self, location):
        return 'app_{app_name}/{user_id}/{iteration_number}/{location}'.format(
            app_name=slugify(self.algorithm.name, allow_unicode=False),
            user_id=self.user_id,
            iteration_number=self.iteration_number,
            location=location
        )

    def get_absolute_url(self):
        return reverse('iteration', kwargs={'pk': self.id})

class LoginHistory(TimestampModel):
    """
    Simple login IP recording model.
    """
    address = models.GenericIPAddressField(verbose_name='IP adresa prijave', protocol='both')
    data = models.TextField(verbose_name='dodatni podaci')

    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, verbose_name='korisnik')

    class Meta:
        verbose_name = 'unos povijesti logiranja'
        verbose_name_plural = 'unosi povijesti logiranja'
        db_table = 'login_history'
        ordering = ('-created',)

    def __str__(self):
        return self.address

app/django/resources/templates/algorithm.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container-fluid">
  <div class="row">

    {% include 'layout/sidebar.html' %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      <h2 class="sub-header">{% trans 'Algoritam' %}</h2>
      <div class="table-responsive">
        <h3>Naziv: <strong>{{ object.name }}</strong></h3>

        <h3>{% trans 'Datotetka za izvršavanje' %}: <a href="{{ object.file.url }}"><strong>{{ object.file }}</strong></a></h3>

        {% if object.document  %}
        <h3>{% trans 'Dokumentacija' %}: <a href="{{ object.document.url }}" target="_blank">{{ object.document }}</a></h3>
        {% endif %}

        {% if object.source  %}
        <h3>{% trans 'Source kod' %}: <a href="{{ object.source.url }}" target="_blank">{{ object.source }}</a></h3>
        {% endif %}

        {% if object.description %}
          <h3>{% trans 'Opis algoritma' %}: </h3>
          <p>{{ object.description }}</p>
        {% endif %}

      </div>

      {% comment %}
      ZASAD NE TREBA

      {% if object.status_message %}
      <h3>Statusna poruka:</h3>
      <p>{{ object.status_message }}</p>
      {% endif %}

      {% endcomment %}
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
      <div class="col-md-3">
        <a href="{% url 'algorithm_list' %}">{% trans 'Povratak na sve algoritme' %}</a>
      </div>
  </div>
</div>

{% endblock %}

app/django/resources/templates/base.html
<!DOCTYPE html>

{% load i18n static tags %}
{% get_current_language as current_code %}
{% get_available_languages as languages %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    <title>rExe</title>
    {% endblock %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>

    {% block nav %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="">rExe</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <p class="navbar-brand">{{ request.user }}</p>
          {% for language_code, language_value in languages %}
            {% if language_code != current_code %}
            <a class="navbar-brand" href="{% translate_url language_code view %}">{% trans 'Promjena jezika: ' %} {{ language_value }}</a>
            {% endif %}
          {% endfor %}
            <a class="navbar-brand" href="{% url 'logout' %}">{% trans 'Logout' %}</a>

          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

app/django/resources/templates/create_iteration.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container-fluid">
  <div class="row">

    {% include 'layout/sidebar.html' %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      <h2 class="sub-header">{% trans 'Nova obrada' %}</h2>
      {{ form.errors }}
      <form class="form" action="{% url 'iteration_create' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <label for="{{ form.algorithm.id_for_label }}" class="sr-only">{{ form.algorithm.label }}</label>
          {{ form.algorithm }}
          <!--<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">-->
          <label for="{{ form.input_data.id_for_label }}" class="sr-only">{{ form.input_data.label }}</label>
          {{ form.input_data }}
          <div class="checkbox">
            <label for="{{ form.mail_on_completion.id_for_label }}">{{ form.mail_on_completion }}{% trans 'Pošalji rezultate na mail' %}</label>
          </div>
          <hr>
          <input class="btn btn-lg btn-primary btn-block" type="submit" value="{% trans 'Pošalji' %}">
        </div>
        <div class="col-md-4"></div>

      </form>
    </div>
  </div>
</div>

{% endblock %}

app/django/resources/templates/home.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container-fluid">
  <div class="row">

    {% include 'layout/sidebar.html' %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      {% if iteration_list %}
      <h2 class="sub-header">{% trans 'Rezultati posljednjih obrada' %}</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>ID</th>
              <th>{% trans 'Algoritam' %}</th>
              <!--<th>Ulazni podaci</th>-->
              <!--<th>Izlazni podaci</th>-->
              <th>{% trans 'Početak' %}</th>
              <th>{% trans 'Završetak' %}</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
          {% for item in iteration_list %}

            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a href="{% url 'iteration' item.id %}">{{ item.id }}</a></td>
              <td><a href="{{ item.algorithm.file.url }}">{{ item.algorithm }}</a></td>
              <!--<td><a href="{{ item.input_data.url }}">{{ item.input_data }}</a></td>-->
              <!--<td>{% if item.output_data %}<a href="{{ item.output_data.url }}">{{ item.output_data }}</a>{% endif %}</td>-->
              <td>{{ item.created|date:"d.m.Y. H:i:s" }}</td>
              <td>{{ item.finished|date:"d.m.Y. H:i:s" }}</td>
              {% if item.started %}
                <td><span class="label label-warning">{{ item.get_status_code_display|upper }}</span></td>
              {% elif item.failed %}
                <td><span class="label label-danger">{{ item.get_status_code_display|upper }}</span></td>
              {% elif item.successful %}
                <td><span class="label label-success">{{ item.get_status_code_display|upper }}</span></td>
              {% endif %}
            </tr>

          {% endfor %}
          </tbody>
        </table>
      </div>
      {% elif algorithm_list %}
      <h2 class="sub-header">{% trans 'Dostupni algoritmi' %}</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>ID</th>
              <th>{% trans 'Algoritam' %}</th>
            </tr>
          </thead>
          <tbody>
          {% for item in algorithm_list %}

            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a href="{% url 'algorithm' item.id %}">{{ item.id }}</a></td>
              <td>{{ item.name }}</td>
            </tr>

          {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <h2 class="sub-header">{% trans 'Trenutno nema obrada' %}</h2>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

app/django/resources/templates/iteration.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container-fluid">
  <div class="row">

    {% include 'layout/sidebar.html' %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      <h2 class="sub-header">{% trans 'Rezultati obrade' %}</h2>
      <div class="table-responsive">
        <h3>{% trans 'Algoritam' %}: <strong>{{ object.algorithm }}</strong></h3>

        {% if object.algorithm.description %}
          <h3>{% trans 'Opis algoritma' %}:</h3>
          <p>{{ object.algorithm.description }}</p>
        {% endif %}

        {% if object.algorithm.document  %}
        <h3>{% trans 'Dokumentacija' %}: <a href="{{ object.algorithm.document.url }}" target="_blank">{{ object.algorithm.document }}</a></h3>
        {% endif %}

        {% if object.algorithm.description %}
          <h3>{% trans 'Opis algoritma' %}:</h3>
          <p>{{ object.algorithm.description }}</p>
        {% endif %}
        <h4>{% trans 'Vrijeme početka izvršavanja' %}: <strong>{{ object.created|date:"d.m.Y. H:i" }}</strong></h4>
        {% if object.failed or object.successful %}
          <h4>{% trans 'Vrijeme završetka izvršavanja' %}: <strong>{{ object.finished|date:"d.m.Y. H:i" }}</strong></h4>
        {% endif %}
        <h4>{% trans 'Status obrade' %}: <strong>{{ object.get_status_code_display|upper }}</strong></h4>

        <div class="col-md-6">
          <h3>{% trans 'Ulazni podaci' %}:</h3>
          {% if object.input_is_image %}
          <a href="{{ object.input_data.url }}" target="_blank"><img src="{{ object.input_data.url }}" alt="" style="width: 100%; height: 100%;"></a>
          {% else %}
            <a href="{{ object.input_data.url }}">{{ object.input_data }}</a>
          {% endif %}
        </div>
        <div class="col-md-6">
          <h3>{% trans 'Izlazni podaci' %}:</h3>
          {% if object.output_is_image %}
          <a href="{{ object.output_data.url }}" target="_blank"><img src="{{ object.output_data.url }}" alt="" style="width: 100%; height: 100%;"></a>
          {% else %}
            {% if object.output_data %}
            <a href="{{ object.output_data.url }}">{{ object.output_data }}</a>
            {% else %}
            <p>{% trans 'Još nisu generirani' %}.</p>
            {% endif %}
          {% endif %}
        </div>
      </div>

      {% comment %}
      ZASAD NE TREBA

      {% if object.status_message %}
      <h3>Statusna poruka:</h3>
      <p>{{ object.status_message }}</p>
      {% endif %}

      {% endcomment %}
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
      <div class="col-md-3">
        <a href="{% url 'home' %}">{% trans 'Povratak na sve rezultate' %}</a>
      </div>
  </div>
</div>

{% endblock %}